baseURL = "https://g3stone.github.io"
languageCode = "zh-cn"
title = "Stone's 个人博客"
theme = "FixIt"

[params]
  # FixIt 主题版本
  version = "0.2.X"
  
  # 网站描述
  description = "这是我的个人博客"
  keywords = ["Hugo", "LoveIt", "博客"]
  
  # 网站默认主题 ("light", "dark", "auto")
  defaultTheme = "auto"
  
  # 页面头部导航栏配置
  [params.header]
    # 桌面端导航栏模式 ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # 移动端导航栏模式 ("fixed", "normal", "auto")
    mobileMode = "auto"
    
  # 页面底部信息配置
  [params.footer]
    enable = true
    # 自定义内容 (支持 HTML 格式)
    custom = ""
    # 是否显示 Hugo 和主题信息
    hugo = true
    # 是否显示版权信息
    copyright = true
    # 是否显示作者
    author = true
    # 网站创立年份
    since = 2025

  # 主页信息设置
  [params.home]
    # RSS 文章数目
    rss = 10
    # 主页个人信息
    [params.home.profile]
      enable = true
      # Gravatar 邮箱，用于优先显示的头像
      gravatarEmail = ""
      # 头像文件路径 (置于 static 目录下)
      avatarURL = "/images/avatar.png"
      # 头像菜单链接的 identifier
      avatarMenu = ""
      # 主页显示头像的 title
      title = "Stone"
      # 主页显示的网站副标题
      subtitle = "在这里分享一些技术和思考"
      # 是否为副标题显示打字机动画
      typeit = true
      # 是否显示社交账号
      social = true

  # 作者配置
  [params.author]
    name = "Stone"
    email = "your@email.com"
    link = ""

# 菜单配置
[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "关于"
    url = "/about/"
    title = ""
    weight = 4

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

